export enum PublicAppRoutes {
  ACCOUNT = '/account',
  ACCOUNT_PROFILE = '/account/profile',
  ACCOUNT_SETTINGS = '/account/settings',
  ACCOUNT_STATS = '/account/stats',
  AUTH_EMAIL_VERIFICATION = '/auth/email-verification',
  AUTH_LOGIN = '/auth/login',
  AUTH_SIGNUP = '/auth/signup',
  BROWSE = '/browse',
  BROWSE_FILTERS = '/browse/filters',
  BUILD_EDIT_TRAINING_PLAN = '/build/edit-training-plan',
  BUILD_EDIT_TRAINING_SESSION = '/build/edit-training-session',
  BUILD_NEW_TRAINING_PLAN = '/build/new-training-plan',
  BUILD_NEW_TRAINING_SESSION = '/build/new-training-session',
  LEGAL_PRIVACY_POLICY = '/legal/privacy-policy',
  LEGAL_TERMS_AND_CONDITIONS = '/legal/terms-and-conditions',
  PRELAUNCH = '/prelaunch',
  TRAIN_DASHBOARD = '/train',
  TRAIN_EDIT_PERSONAL_QUEUE = '/train/edit-personal-queue',
  TRAIN_TRAINING_PLAN = '/train/plan',
  TRAIN_TRAINING_SESSION = '/train/session',
}

export const NoNavBarUrls = [
  PublicAppRoutes.PRELAUNCH,
  PublicAppRoutes.AUTH_LOGIN,
  PublicAppRoutes.AUTH_SIGNUP,
  PublicAppRoutes.AUTH_EMAIL_VERIFICATION,
  PublicAppRoutes.TRAIN_TRAINING_SESSION,
  PublicAppRoutes.BUILD_EDIT_TRAINING_SESSION,
  PublicAppRoutes.BUILD_NEW_TRAINING_SESSION,
  PublicAppRoutes.TRAIN_TRAINING_PLAN,
  PublicAppRoutes.BUILD_NEW_TRAINING_PLAN,
  PublicAppRoutes.BUILD_EDIT_TRAINING_PLAN,
];